Document: libapache2-mod-vhs
Title: Debian libapache2-mod-vhs Manual
Author: <insert document author here>
Abstract: This manual describes what libapache2-mod-vhs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libapache2-mod-vhs/libapache2-mod-vhs.sgml.gz

Format: postscript
Files: /usr/share/doc/libapache2-mod-vhs/libapache2-mod-vhs.ps.gz

Format: text
Files: /usr/share/doc/libapache2-mod-vhs/libapache2-mod-vhs.text.gz

Format: HTML
Index: /usr/share/doc/libapache2-mod-vhs/html/index.html
Files: /usr/share/doc/libapache2-mod-vhs/html/*.html
